#!/bin/bash

_gm_policy_test_number_6() {
  local num; num=$1
  local policy_yaml=$(_get_policy_file $num)

  _msg "Test #$num: check role prefix ... "

  cat <<'EOF' >"$policy_yaml"
- username: jimi
  roles:
    - dwh_song_write
- username: david
  roles:
    - dwh_song_read
EOF

  local get_policy_yaml
  get_policy_yaml=$(dirname $policy_yaml)/policy_get.yaml

  local get_policy_prefix_yaml
  get_policy_prefix_yaml=$(dirname $policy_yaml)/policy_prefix.yaml

  _policy apply "$policy_yaml" || exit 1
  GM_DATABASE_ROLE_PREFIX='meddle\_' _policy get > "$get_policy_yaml" || exit 1

  cat <<'EOF' >"$get_policy_prefix_yaml"
[]
EOF

  _equal "$get_policy_yaml" "$get_policy_prefix_yaml"

  _exitcode "$?"
}
