#!/bin/bash

_gm_policy_test_number_4() {
  local num; num=$1
  local policy_yaml=$(_get_policy_file $num)

  _msg "Test #$num: add multple roles for multiple users ... "

  cat <<'EOF' >"$policy_yaml"
- username: jimi
  roles:
    - dwh_song_read
    - dwh_song_write
- username: stevie
  roles:
    - dwh_song_read
- username: david
  roles:
    - dwh_band_read
    - dwh_band_write
EOF
  _compare "$policy_yaml"
}

_gm_policy_test_number_5() {
  local num; num=$1
  local policy_yaml=$(_get_policy_file $num)

  _msg "Test #$num: remove multple roles for multiple users ... "

  cat <<'EOF' >"$policy_yaml"
- username: jimi
  roles:
    - dwh_song_write
- username: david
  roles:
    - dwh_song_read
EOF
  _compare "$policy_yaml"
}

