#!/bin/bash

export POSTGRES_DOCKER_CONTAINER=${POSTGRES_DOCKER_CONTAINER:-postgres}
export POSTGRES_USER=${POSTGRES_USER:-dwh}
export POSTGRES_DATABASE=${POSTGRES_DATABASE:-dwh}
export GM_DATABASE_TYPE=postgres
export GM_POSTGRES_CONN_STRING='postgres://dwh:dwh@localhost:5432/dwh'

_exec() {
  docker exec -ti "$POSTGRES_DOCKER_CONTAINER" "$@"
}

_psql_read() {
  _exec cat /root/output
}

_psql() {
  _exec psql --output=/root/output -U "$POSTGRES_USER" -d "$POSTGRES_DATABASE" "$@"
}

_role() {
  $GM_BIN role "$@"
}

_cmp() {
  cmp -s "$@"
}

_get_roles_file() {
  local num; num=$1
  
  mkdir -p "$TEST_DIR/roles/$num"
  echo $TEST_DIR/roles/$num/roles.yaml
}

_done() {
  echo -e "\e[32mdone\e[0m"  
}

_failed() {
  echo -e "\e[31mfailed\e[0m"  
}

_compare() {
  local input; input=$1
  local current; current="$(dirname $input)/get.yaml"

  _role apply "$input" || exit 1
  _role get > "$current" || exit 1

 local exitcode; exitcode=0

 if ! _cmp "$input" "$current"; then
   exitcode=1
 fi

 if [[ $exitcode -eq 0 ]]; then
   _done
 else
   _failed
 fi

 return $exitcode
}
