#!/bin/bash

_role() {
  $GM_BIN role "$@"
}

_get_role_file() {
  local num; num=$1
 
  _get_type_yaml_file role $num
}

_equal() {
  _role equal "$@"
}

_compare() {
  local input; input=$1
  local compare_with; compare_with=$2   

  local current; current="$(dirname $input)/get.yaml"
  local exitcode; exitcode=0

  _role apply "$input" &>/dev/null || exit 1
  _role get > "$current" || exit 1

  # check if compare_with is not empty then use it
  # as a first comparable parameter.
  [[ -n $compare_with ]] && input=$compare_with

  if ! _equal "$input" "$current"; then
    exitcode=1

    diff "$input" "$current"
  fi

  if [[ $exitcode -eq 0 ]]; then
    _done
  else
    _failed
  fi

  return $exitcode
}
