#!/bin/bash

_gm_role_test_number_14() {
  local num; num=$1
  local role_yaml=$(_get_role_file $num)

  echo -n "Test #$num: check role prefix ... "

  cat <<'EOF' >"$role_yaml"
- name: dwh_song_read
  schemas:
    - schema: song
      grants:
        - create
        - usage
    - schema: band
      grants:
        - usage
- name: dwh_song_write
  schemas:
    - schema: song
      grants:
        - create
        - usage
EOF

  local get_role_yaml
  get_role_yaml=$(dirname $role_yaml)/role_get.yaml

  local get_role_prefix_yaml
  get_role_prefix_yaml=$(dirname $role_yaml)/role_prefix.yaml

  _role apply "$role_yaml" || exit 1
  GM_DATABASE_ROLE_PREFIX='meddle\_' _role get > "$get_role_yaml" || exit 1

  cat <<'EOF' > "$get_role_prefix_yaml"
[]
EOF

  _equal "$get_role_yaml" "$get_role_prefix_yaml"

  _exitcode "$?"
}
