#!/bin/bash

source tests/postgres/role/_functions

_test_number_1() {
  local num; num=$1
  local roles_yaml=$(_get_roles_file $num)

  echo -n "Test #$num: add usage,create grants to song schema ... "

  cat <<'EOF' >"$roles_yaml"
- name: dwh_song_read
  schemas:
    - schema: song
      grants:
        - create
        - usage
EOF
  _compare "$roles_yaml"
}

_test_number_2() {
  local num; num=$1
  local roles_yaml=$(_get_roles_file $num)

  echo -n "Test #$num: remove create grant from song schema ... "

  cat <<'EOF' >"$roles_yaml"
- name: dwh_song_read
  schemas:
    - schema: song
      grants:
        - usage
EOF
  _compare "$roles_yaml"
}

_test_number_3() {
  local num; num=$1
  local roles_yaml=$(_get_roles_file $num)
  echo -n "Test #$num: remove usage grant from song schema ... "

  cat <<'EOF' >"$roles_yaml"
- name: dwh_song_read
  schemas:
    - schema: song
      grants:
EOF
  _compare "$roles_yaml"
}

_test_number_4() {
  local num; num=$1
  local roles_yaml=$(_get_roles_file $num)
  echo -n "Test #$num: remove whole dwh_song_read role ... "

  cat <<'EOF' >"$roles_yaml"
[]
EOF
  _compare "$roles_yaml"
}

_test_number_5() {
  local num; num=$1
  local roles_yaml=$(_get_roles_file $num)
  echo -n "Test #$num: add band,song schemas ... "

  cat <<'EOF' >"$roles_yaml"
- name: dwh_song_read
  schemas:
    - schema: band
      grants:
        - create
        - usage
    - schema: song
      grants:
        - usage
EOF
  _compare "$roles_yaml"
}

_test_number_6() {
  local num; num=$1
  local roles_yaml=$(_get_roles_file $num)
  echo -n "Test #$num: remove song schema ... "

  cat <<'EOF' >"$roles_yaml"
- name: dwh_song_read
  schemas:
    - schema: band
      grants:
        - create
        - usage
EOF
  _compare "$roles_yaml"
}

_test_number_7() {
  local num; num=$1
  local roles_yaml=$(_get_roles_file $num)
  echo -n "Test #$num: add song schema to existing ... "

  cat <<'EOF' >"$roles_yaml"
- name: dwh_song_read
  schemas:
    - schema: band
      grants:
        - create
        - usage
    - schema: song
      grants:
        - create
        - usage
EOF
  _compare "$roles_yaml"
}

_test_number_8() {
  local num; num=$1
  local roles_yaml=$(_get_roles_file $num)
  echo -n "Test #$num: remove create grant from song schema ... "

  cat <<'EOF' >"$roles_yaml"
- name: dwh_song_read
  schemas:
    - schema: band
      grants:
        - create
        - usage
    - schema: song
      grants:
        - usage
EOF
  _compare "$roles_yaml"
}

_test_number_9() {
  local num; num=$1
  local roles_yaml=$(_get_roles_file $num)
  echo -n "Test #$num: remove usage grant from band schema ... "

  cat <<'EOF' >"$roles_yaml"
- name: dwh_song_read
  schemas:
    - schema: band
      grants:
        - create
    - schema: song
      grants:
        - usage
EOF
  _compare "$roles_yaml"
}
